name: ai_tutor_storage
services:
  local_dev_atlas:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: local_dev_atlas
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb/data:/data/db # Maps the 'mongodb/data' directory on your host to '/data/db' in the container
      - ./mongodb/config:/data/configdb # Maps the 'mongodb/config' directory on your host to '/data/configdb' in the container

volumes:
  data:
  config:
